AWS_SECRET = "prod/SAAWS"
SAP_SECRET = 'prod/SAP'
SLACK_TOKEN = 'prod/Slack'
# Columns to rename in each transformation # BELLOW PREPARATIONS FOR V2 OF THIS ETL
# VBAK_RENAME = {
#     'Criado em': 'criado_em',
#     'Criado por': 'criado_por',
#     'Criado/a': 'criado_por',
#     'Criado_a': 'criado_por',
#     'Ctg.doc.': 'categoria_documento',
#     'BlqR': 'bloqueio_remessa',
#     'Doc.venda': 'documento_vendas',
#     'TpDV': 'tipo_documento_vendas',
#     'BF': 'bloqueio_documento_faturamento',
#     'Val.líq.': 'valor_liquido',
#     'OrgV': 'organizacao_vendas',
#     'CDst': 'canal_distribuicao',
#     'SA': 'setor_atividade',
#     'Cond.doc.': 'numero_condicao_documento',
#     'Prb': 'probabilidade',
#     'Referência cliente': 'referencia_cliente',
#     'Ref_cliente': 'referencia_cliente',
#     'Ref.cliente': 'referencia_cliente',
#     'Emis.ordem': 'emissor_ordem',
#     'Modif.por': 'modificado_por'
# }

# KNA1_RENAME = {
#     'Cliente': 'id_cliente',
#     'P/R': 'chave_pais_regiao',
#     'CódigoPost': 'codigo_postal',
#     'CDst': 'canal_distribuicao',
#     'Rg': 'regiao',
#     'Crit.pesq.': 'termo_pesquisa',
#     'ConcPesq': 'termo_pesquisa',
#     'Telefone 1': 'telefone_1',
#     'Nome 1': 'nome_1',
#     'Nome 2': 'nome_2',
#     'Endereço': 'endereco',
#     'Cidade': 'cidade',
#     'Bairro': 'bairro',
#     'Idioma': 'idioma',
#     'Rua': 'rua',
#     'Dt.abert.': 'data_criacao',
#     'Autor': 'criado_por',
#     'Criado por': 'criado_por',
#     'PessFísica': 'pessoa_fisica',
#     'DomFiscal': 'domicilio_fiscal',
#     'CNAE fisc.': 'cnae_fiscal',
#     'TpDecImp.': 'tipo_declaracao_imposto',
#     'Fatur.': 'faturamento_anual',
#     'NºIdFisc-2': 'cpf',
#     'Nº ID fiscal 1': 'cnpj',
#     'NºIdFisc-1': 'cnpj',
#     'CaracLegal': 'natureza_juridica'
# }

# KNVV_RENAME = {
#     'Cliente': 'id_cliente',
#     'OrgV': 'organizacao_vendas',
#     'CDst': 'canal_distribuicao',
#     'SA': 'setor_atividade',
#     'Criado em': 'data_criacao',
#     'Criado por': 'criado_por',
#     'EsCl': 'esquema_cliente',
#     'Região': 'regiao_vendas',
#     'GPC': 'grupo_precos_cliente',
#     'GCCC': 'grupo_class_conta_cli'
# }

# J_1BNFDOC_RENAME = {
#     'Nº doc.': 'numero_documento',
#     'CN': 'categoria_nota_fiscal',
#     'D': 'tipo_documento',
#     'M': 'direcao_movimento',
#     'Data doc.': 'data_documento',
#     'Dt.lçto.': 'data_lancamento',
#     'Criado em': 'data_criacao',
#     'Criad.às': 'criado_as',
#     'Criado por': 'criado_por',
#     'Usuário': 'criado_por',
#     'Modif.em': 'modificado_em',
#     'Modif.às': 'modificado_as',
#     'Modif.por': 'modificado_por',
#     'Usuário    .1': 'modificado_por',
#     'Nº NF': 'numero_nota_fiscal',
#     'Moeda': 'moeda_documento',
#     'Empr': 'empresa',
#     'FP': 'nf_funcao_parceiro',
#     'ID parc.': 'id_parceiro',
#     'P': 'tipo_parceiro',
#     'Estornado': 'estornado',
#     'Dt.estorno': 'data_estorno',
#     'DocSubseq.': 'existe_documento_subsequente',
#     'Doc.orig.': 'numero_documento_original',
#     'Data base': 'data_base_prazo_pagamento',
#     'Val.total': 'valor_total_inclunido_imposto',
#     'Nº NFS-e': 'numero_nfse_servicos',
#     'Nº NF-e': 'numero_nfe_servicos',
#     'Stat.doc.': 'status_documento',
#     'Cód.status': 'codigo_status',
#     'PessFísica': 'pessoa_fisica',
#     'Code CGC': 'codigo_cgc',
#     'CPF': 'numero_cpf',
#     'DomFiscal': 'domicilio_fiscal',
#     'E-mail': 'endereco_email',
#     'Data proc.': 'data_processamento',
#     'H.procmto.': 'hora_processamento',
#     'Reg.hora criação': 'registro_hora_criacao',
#     'Reg.hora': 'registro_hora_criacao'
# }

# J_1BNFLIN_RENAME = {
#     'Nº doc.': 'numero_documento',
#     'NºIt': 'numero_item_documento',
#     'Material': 'material',
#     'ÁrAv': 'area_avaliacao',
#     'Texto breve material': 'texto_breve_material',
#     'TxtBreveMaterial': 'texto_breve_material',
#     'Ref_origem': 'referencia_documento_origem',
#     'Ref.doc.origem': 'referencia_documento_origem',
#     'Valor': 'valor_liquido',
#     'Cen.': 'centro',
#     'Pedido': 'pedido',
#     'CtaAnalít.': 'codigo_conta_analitica_contabil_debito_credito',
#     'LC116 cód.': 'lc_116_codigo_tipo_servico',
#     'Cen.lucro': 'centro_lucro'
# }

# VBRK_RENAME = {
#     'Doc.fat': 'documento_faturamento',
#     'Doc_fat': 'documento_faturamento',
#     'TipFt': 'tipo_documento_faturamento',
#     'OrgV': 'organizacao_vendas',
#     'CDst': 'canal_distribuicao',
#     'SA': 'setor_atividade',
#     'Criado em': 'criado_em',
#     'Cond.doc.': 'numero_condicao_documento',
#     'Dt.fatur.': 'data_faturamento',
#     'Nº doc.': 'numero_documento',
#     'Ano': 'exercicio',
#     'StCn': 'status_lancamento',
#     'MP': 'forma_pagamento',
#     'Val.líq.': 'valor_liquido',
#     'Hor.rg.': 'hora_registro',
#     'Pagador': 'pagador',
#     'Modif.em': 'modificado_em',
#     'Referência': 'referencia',
#     'Atribuição': 'atribuicao',
#     'Registro da hora': 'registro_hora',
#     'SC': 'status_lancamento',
#     'SG': 'status_global',
#     'St.comp': 'status_compensacao',
#     'St_comp': 'status_compensacao',
#     'Status': 'status',
#     'Mont.imp.': 'montante_imposto',
#     'Tipo': 'tipo_documento'
# }

# VBRP_RENAME = {
#     'Doc.fat.': 'documento_faturamento',
#     'TipFt': 'tipo_documento_faturamento',
#     'CDst': 'canal_distribuicao',
#     'DtPrestSer': 'data_prestacao_servico',
#     'Doc.venda': 'documento_vendas',
#     'Cond.doc.': 'numero_condicao_documento',
#     'Dt.fatur.': 'data_faturamento',
#     'Item': 'item',
#     'Denominação de item': 'denominacao_item',
#     'Denominacao_itens': 'denominacao_item',
#     'CtgI': 'categoria_item',
#     'GCCM': 'grupo_class_cont_mat',
#     'Val.líq.': 'valor_liquido',
#     'Cen.lucro': 'centro_lucro',
#     'Dev': 'devolucao',
#     'Pagador': 'pagador',
#     'Mat.inser.': 'material_inserido',
#     'Mont.imp.': 'montante_imposto',
#     'Ctg.doc.': 'categoria_documento_sd',
#     'OrgV': 'organizacao_vendas',
#     'Empr': 'empresa',
#     'DF estorno': 'documento_faturamento_estornado',
#     'Status': 'status'
# }

# VBAP_RENAME = {
#     'Criado em': 'criado_em',
#     'Criado por': 'criado_por',
#     'Criado/a': 'criado_por',
#     'GCCM': 'grupo_class_cont_mat',
#     'Denominação it.': 'denominacao_item',
#     'Denominação de item': 'denominacao_item',
#     'CtgI': 'categoria_item',
#     'Subtotal 1': 'subtotal_1',
#     'Modif.em': 'modificado_em',
#     'SA.1': 'setor_atividade',
#     'St.recusa': 'status_recusa',
#     'Rc': 'motivo_recusa',
#     'BF': 'bloqueio_documento_faturamento',
#     'Cen.': 'centro',
#     'Dt.fatur.': 'data_faturamento',
#     'Cen.lucro': 'centro_lucro',
#     'Mont.imp.': 'montante_imposto',
#     'Dt.estim.': 'data_pagamento_estimado',
#     'Doc.venda': 'documento_vendas',
#     'TpDV': 'tipo_documento_vendas',
#     'BF': 'bloqueio_documento_faturamento',
#     'Val.líq.': 'valor_liquido',
#     'OrgV': 'organizacao_vendas',
#     'SA': 'setor_atividade',
#     'Cond.doc.': 'numero_condicao_documento',
#     'Prb': 'probabilidade',
#     'Referência cliente': 'referencia_cliente',
#     'Ref.cliente': 'referencia_cliente',
#     'Emis.ordem': 'emissor_ordem',
#     'Modif.por': 'modificado_por'
# }

# BKPF_RENAME = {
#     'Empr': 'empresa',
#     'Data doc.': 'data_documento',
#     'Data lçto.': 'data_lancamento',
#     'Período': 'periodo',
#     'Entrado em': 'entrado_em',
#     'Usuário': 'nome_usuario',
#     'Chave referência': 'chave_referencia',
#     'Tx.câmbio3': 'taxa_cambio_3',
#     'DEs': 'documento_estorno',
#     'Est': 'estornado',
#     'Tipo': 'tipo_documento',
#     'Nº doc.': 'numero_documento',
#     'Ano': 'exercicio'
# }

# BSEG_RENAME = {
#     'Empr': 'empresa',
#     'Nº doc.': 'numero_documento',
#     'Ano': 'exercicio',
#     'Itm': 'item',
#     'Compensaç.': 'data_compensacao_1',
#     'DtCompens.': 'data_compensacao_2',
#     'Dt.compen.': 'data_compensacao_2',
#     'DocCompens': 'documento_compensacao',
#     'CL': 'chave_lancamento',
#     'TpCta': 'tipo_conta',
#     'D/C': 'debito_credito',
#     'MontMdFnc.': 'montante_moeda_funcional',
#     'Dt.efetiva': 'adata_efetiva',
#     'Atribuição': 'atribuicao',
#     'Texto': 'texto',
#     'Montante': 'montante_alocado',
#     'DtPlanej.': 'data_planejamento',
#     'Cta.Razão': 'conta_razao_1',
#     'CtaRz.': 'conta_razao_2',
#     'Cliente': 'cliente',
#     'Fornecedor': 'fornecedor',
#     'CPgt': 'condicoes_pagamento',
#     'Mont.MI 3': 'montante_mi_3',
#     'Mont.MI3': 'montante_mi_3',
#     'Anular compensação': 'anular_compensacao',
#     'Cta.alt.': 'numero_conta_alternativa',
#     'ACCr': 'area_controle_credito',
#     'Ref.pgto.': 'referencia_pagamento',
#     'ItCm': 'item_compensacao',
#     'Chave referência': 'chave_referencia',
#     'Chave refer.': 'chave_referencia',
#     'Tipo fluxo': 'tipo_fluxo'
# }